# Generated by Django 5.1 on 2024-09-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_options_user_date_joined_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=255)),
                ('bmi', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('bmr', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('food_type', models.CharField(max_length=255)),
                ('is_premium', models.BooleanField()),
            ],
        ),
    ]
