# Generated by Django 5.1 on 2024-09-19 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='is_premium',
        ),
    ]
